from __future__ import annotations

import asyncio
from pathlib import Path

import fluxer as fluxer
from fluxer.ext import commands

from bot import FullFeatureBot
from cogs.shared import require_mutations


class MessagingFeatures(commands.Cog):
    def __init__(self, bot: FullFeatureBot):
        super().__init__(bot)

    @commands.command(name="send_text")
    async def send_text(self, ctx: commands.Context, channel: fluxer.Channel, *, content: str):
        """Send text to a target channel."""
        sent = await channel.send(content)
        await ctx.reply(f"Sent message id={sent.id}")

    @commands.command(name="send_embed")
    async def send_embed(self, ctx: commands.Context, channel: fluxer.Channel, *, title: str):
        """Send an embed to a target channel with mentions disabled."""
        embed = fluxer.Embed(
            title=title,
            description="Generated by full example",
            color=fluxer.Colour.blurple().value,
        ).add_field(name="author", value=ctx.author.display_name, inline=False)
        allowed_mentions = fluxer.AllowedMentions.none()
        message = await channel.send(
            embed=embed,
            allowed_mentions=allowed_mentions.to_dict(),
        )
        await ctx.reply(f"Embed sent with id={message.id}")

    @commands.command(name="fetch_message")
    async def fetch_message(self, ctx: commands.Context, channel: fluxer.Channel, message_id: int):
        """Fetch a message by channel and message ID."""
        message = await channel.fetch_message(message_id)
        await ctx.reply(f"Fetched: id={message.id} content={message.content!r}")

    @commands.command(name="reply_message")
    async def reply_message(
        self,
        ctx: commands.Context,
        channel: fluxer.Channel,
        message_id: int,
        *,
        content: str,
    ):
        """Reply to an existing message by ID."""
        message = await channel.fetch_message(message_id)
        reply = await message.reply(content)
        await ctx.reply(f"Reply sent id={reply.id}")

    @commands.command(name="edit_message")
    async def edit_message(
        self,
        ctx: commands.Context,
        channel: fluxer.Channel,
        message_id: int,
        *,
        content: str,
    ):
        """Edit an existing message by ID. Requires mutations to be enabled."""
        require_mutations(self.bot)
        message = await channel.fetch_message(message_id)
        edited = await message.edit(content)
        await ctx.reply(f"Edited message id={edited.id}")

    @commands.command(name="delete_message")
    async def delete_message(self, ctx: commands.Context, channel: fluxer.Channel, message_id: int):
        """Delete an existing message by ID. Requires mutations to be enabled."""
        require_mutations(self.bot)
        message = await channel.fetch_message(message_id)
        await message.delete()
        await ctx.reply("Message deleted.")

    @commands.command(name="message_ack")
    async def message_ack(self, ctx: commands.Context, channel: fluxer.Channel, message_id: int):
        """Acknowledge or mark one message as read."""
        message = await channel.fetch_message(message_id)
        await message.ack()
        await ctx.reply("Message acknowledged.")

    @commands.command(name="message_save")
    async def message_save(self, ctx: commands.Context, channel: fluxer.Channel, message_id: int):
        """Save a message for the current user."""
        message = await channel.fetch_message(message_id)
        await message.save()
        await ctx.reply("Message saved.")

    @commands.command(name="message_unsave")
    async def message_unsave(self, ctx: commands.Context, channel: fluxer.Channel, message_id: int):
        """Remove a saved message for the current user."""
        message = await channel.fetch_message(message_id)
        await message.unsave()
        await ctx.reply("Message unsaved.")

    @commands.command(name="message_pin")
    async def message_pin(self, ctx: commands.Context, channel: fluxer.Channel, message_id: int):
        """Pin a message. Requires mutations to be enabled."""
        require_mutations(self.bot)
        message = await channel.fetch_message(message_id)
        await message.pin()
        await ctx.reply("Message pinned.")

    @commands.command(name="message_unpin")
    async def message_unpin(self, ctx: commands.Context, channel: fluxer.Channel, message_id: int):
        """Unpin a message. Requires mutations to be enabled."""
        require_mutations(self.bot)
        message = await channel.fetch_message(message_id)
        await message.unpin()
        await ctx.reply("Message unpinned.")

    @commands.command(name="channel_pins")
    async def channel_pins(self, ctx: commands.Context, channel: fluxer.Channel, limit: int = 10):
        """List pinned messages for a channel."""
        pins = await channel.fetch_pinned_messages(limit=limit)
        await ctx.reply(f"Pinned messages fetched: {len(pins)}")

    @commands.command(name="ack_pins")
    async def ack_pins(self, ctx: commands.Context, channel: fluxer.Channel):
        """Acknowledge a channel's pin notifications."""
        await channel.ack_pins()
        await ctx.reply("Pin notifications acknowledged.")

    @commands.command(name="history")
    async def history(self, ctx: commands.Context, channel: fluxer.Channel, limit: int = 5):
        """Show recent message history for a channel."""
        items = []
        async for message in channel.history(limit=limit):
            items.append(f"{message.id}:{message.author.display_name}")
        await ctx.reply(f"History sample ({len(items)}): {' | '.join(items)}")

    @commands.command(name="purge_contains")
    async def purge_contains(
        self, ctx: commands.Context, channel: fluxer.Channel, needle: str, limit: int = 50
    ):
        """Delete recent messages whose content contains text."""
        require_mutations(self.bot)
        deleted = await channel.purge(
            limit=limit,
            check=lambda message: bool(message.content and needle in message.content),
            bulk=True,
        )
        await ctx.reply(f"Purged {len(deleted)} messages.")

    @commands.command(name="bulk_delete")
    async def bulk_delete(self, ctx: commands.Context, channel: fluxer.Channel, *, message_ids: str):
        """Bulk-delete comma-separated message IDs from a channel."""
        require_mutations(self.bot)
        ids = [int(part.strip()) for part in message_ids.split(",") if part.strip()]
        await channel.delete_messages(ids)
        await ctx.reply(f"Bulk delete sent for {len(ids)} IDs.")

    @commands.command(name="react_add")
    async def react_add(
        self, ctx: commands.Context, channel: fluxer.Channel, message_id: int, emoji: str
    ):
        """Add an emoji reaction to a message."""
        require_mutations(self.bot)
        message = await channel.fetch_message(message_id)
        await message.add_reaction(emoji)
        await ctx.reply("Reaction added.")

    @commands.command(name="react_remove")
    async def react_remove(
        self, ctx: commands.Context, channel: fluxer.Channel, message_id: int, emoji: str
    ):
        """Remove your emoji reaction from a message."""
        require_mutations(self.bot)
        message = await channel.fetch_message(message_id)
        await message.remove_reaction(emoji)
        await ctx.reply("Reaction removed.")

    @commands.command(name="react_clear")
    async def react_clear(self, ctx: commands.Context, channel: fluxer.Channel, message_id: int):
        """Clear all reactions from a message."""
        require_mutations(self.bot)
        message = await channel.fetch_message(message_id)
        await message.clear_reactions()
        await ctx.reply("Reactions cleared.")

    @commands.command(name="trigger_typing")
    async def trigger_typing(self, ctx: commands.Context, channel: fluxer.Channel):
        """Send a one-shot typing indicator to a channel."""
        await channel.trigger_typing()
        await ctx.reply("Typing pulse sent.")

    @commands.command(name="typing_block")
    async def typing_block(
        self, ctx: commands.Context, channel: fluxer.Channel, seconds: float = 3.0
    ):
        """Hold a typing indicator for a few seconds."""
        async with channel.typing():
            await asyncio.sleep(seconds)
        await ctx.reply("Typing context manager demo complete.")

    @commands.command(name="attachment_plan")
    async def attachment_plan(self, ctx: commands.Context, channel: fluxer.Channel, file_path: str):
        """Request presigned upload URLs for a local file path."""
        file = fluxer.File(Path(file_path))
        spec = file.to_upload_spec(id=0)
        plan = await channel.request_attachment_uploads([spec])
        await ctx.reply(f"Attachment plan generated for {len(plan.attachments)} upload(s).")

    @commands.command(name="attachment_complete")
    async def attachment_complete(
        self,
        ctx: commands.Context,
        channel: fluxer.Channel,
        attachment_id: int,
        upload_filename: str,
    ):
        """Complete an attachment upload with preuploaded part metadata."""
        completed = await channel.complete_attachment_uploads(
            [{"id": attachment_id, "upload_filename": upload_filename}]
        )
        await ctx.reply(f"Completed uploads count={len(completed.uploads)}")

    @commands.command(name="search_messages")
    async def search_messages(self, ctx: commands.Context, *, query: str):
        """Search messages using Fluxer's message search endpoint."""
        result = await self.bot.search_messages(query=query, limit=10)
        await ctx.reply(f"Search returned {len(result.messages)} message(s).")

    @commands.command(name="partial_fetch")
    async def partial_fetch(self, ctx: commands.Context, channel: fluxer.Channel, message_id: int):
        """Fetch a message through a PartialMessage wrapper."""
        partial = channel.get_partial_message(message_id)
        message = await partial.fetch()
        await ctx.reply(f"Partial fetched message content={message.content!r}")


async def setup(bot: FullFeatureBot):
    await bot.add_cog(MessagingFeatures(bot))
